### ISSUE TITLE
Use package.json instead of remote()?

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#1]
I saw a thread at https://github.com/yeoman/generator/issues/381#issuecomment-26994715 relating to yeoman generators. If I understand correctly you can use package.json to include the content of the generators in the package instead of using `this.remote`.

@shirhatti thoughts?

**Comment by shirhatti** [comment]
Reading through that thread I got the impression that using `package.json` seemed like a hacky way to deal with private repos.

`this.remote` still seems to be the preferred way allowing us to update the samples out-of-band with the generator

**Comment by sayedihashimi** [comment]
@shirhatti thanks for checking. Closing now.
