### ISSUE TITLE
Does not exit gracefully when K runtime is not installed

### ISSUE THREAD

**Issue by shirhatti** [ligershark/generator-aspnet#10]
If the k runtime is not present on your machine, the generator will crash will trying to execute `kpm restore`

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
```

**Comment by shirhatti** [comment]
Should be an easy fix. Just need to surround [index.js#L91](https://github.com/ligershark/generator-aspnet/blob/master/app/index.js#L91) with a try/catch block

**Comment by sayedihashimi** [comment]
I wrapped the call to `kpm restore` in a try/catch.
