### ISSUE TITLE
Error while creating a new project (events.js:72)

### ISSUE THREAD

**Issue by dmeijboom** [ligershark/generator-aspnet#11]
sudo yo aspnet
Password:

```
 _-----_
|       |    .--------------------------.
|--(o)--|    | Welcome to the marvelous |
```

   `---------´   |     Aspnet generator!    |
    ( _´U`_ )    '--------------------------'
    /**_A**_\  
     |  ~  |  
   **'._**.'__  
 ´   `|° ´ Y` 

[?] What type of application do you want to create? MVC Application
[?] What's the name of your ASP.NET application? TestApp

```
 info ... Fetching http://github.com/ligershark/aspnet_vnext_samples/archive/master.tar.gz ...
 info This might take a few moments
```

..✔ Done in /Users/dmeijboom/.cache/yeoman/ligershark/aspnet_vnext_samples/master

   create NuGet.config
   create TestApp/Controllers/HomeController.cs
   create TestApp/Models/User.cs
   create TestApp/Startup.cs
   create TestApp/Views/Home/Index.cshtml
   create TestApp/Views/Shared/_Layout.cshtml
   create TestApp/project.json
/Users/dmeijboom/.cache/yeoman

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by sayedihashimi** [comment]
I just fixed this in the `master` branch with commit 016171db5c03eedd624fdc748ff86607949ac61e. Could you help me test this change to see if it works for you? Once it's verified I'll release it. To test this it's easy just do the following. It assumes that you have node/npm installed.
1. Clone this repo locally
2. `cd` to the repo folder
3. Execute the command `npm link`
4. Run the generators and see if you get an error

To undo this you can execute the command `npm rm -g generator-aspnet`.

**Comment by dmeijboom** [comment]
Yes, I will do this tonight!

**Comment by CelsoSantos** [comment]
I too have this problem.

I'm on Yosemite and always get the exact same error

**Comment by sayedihashimi** [comment]
@CelsoSantos do you have the asp.net command line tools installed? You can find more info at https://github.com/aspnet/home. 
I think this problem is because it tries to do a `kpm restore` after `yo aspnet` completes.

**Comment by CelsoSantos** [comment]
Hi sayed,

You were right. For some reason, although I had already begun the install process for asp.net but didn't end it (specifically, the last step). I just ran that last step and now everything works fine.

Thank you
