### ISSUE TITLE
Nancy generator gets warning if invoked in same folder as previously executed

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#14]
Try the following.
1. yo aspnet and create a console project
2. yo aspnet and create a web project
3. yo aspnet and create a nancy project

On the step where you create a nancy project you get the warning below. I believe this is because we copy two different nuget.config files. See https://github.com/ligershark/generator-aspnet/blob/master/app/index.js#L92. 

@jchannon could you take a look?

![nancy](https://cloud.githubusercontent.com/assets/1283154/4211827/35fcbf90-3891-11e4-8820-ad65043084a4.png)

**Comment by jchannon** [comment]
My thoughts would be to create another folder so when you choose an option it creates like so:

```
ConsoleApplication1
  NuGet.config
  ConsoleApplication1
    Programs.cs
```

That way each option you choose doesn't use the same Nuget.config.

Thoughts?

**Comment by sayedihashimi** [comment]
I think that's going to lead to too many `NuGet.config` files. I checked both repositories and both files have the exact same content. I see no reason to special case the nancy generator in this case. in `index.js` we currently have

``` javascript
 if (this.type === 'nancy') {
this.copy(this.cacheRoot() + '/jchannon/aspnet_vnext_samples/master/NuGet.config', 'NuGet.config');
} else {
this.copy(this.cacheRoot() + '/ligershark/aspnet_vnext_samples/master/NuGet.config', 'NuGet.config');
}
```

I think we can avoid the error by changing this to.

``` javascript
this.copy(this.cacheRoot() + '/ligershark/aspnet_vnext_samples/master/NuGet.config', 'NuGet.config');
```

**Comment by sayedihashimi** [comment]
@jchannon FYI `nuget.config` needs to be at the "solution root" not in the project directory so it wouldn't make sense to drop them in the folder as `project.json`. See https://github.com/ligershark/generator-aspnet/issues/17 for more issues if interested.

I will remove the if statement for the `nuget.config` as I mentioned above.

**Comment by jchannon** [comment]
Okey dokey

Will try and look at the others
