### ISSUE TITLE
Create nested options

### ISSUE THREAD

**Issue by jchannon** [ligershark/generator-aspnet#16]
At the moment each option is a list item such as Console App, Web App, MVC App, Nancy App.

I think we should find a way to display the options nested so if you choose Console App you are then given the choice of Nancy Console App and WebApi App

**Comment by sayedihashimi** [comment]
Feel free to prototype it so we can try out the experience.

**Comment by sayedihashimi** [comment]
Migrated to https://github.com/OmniSharp/generator-aspnet/issues/27
