### ISSUE TITLE
Add scaffolding to web templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#19]
We should add the scaffolding components to web projects. We need to make the following changes to `project.json` for the web projects.
1. Add `"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-*"` in dependencies
2. Add `"gen": "Microsoft.Framework.CodeGeneration"` in the commands section

**Comment by spboyer** [comment]
@sayedihashimi  @rustd PR submitted https://github.com/ligershark/aspnet_vnext_samples/pull/12

**Comment by sayedihashimi** [comment]
Added https://github.com/OmniSharp/generator-aspnet
