### ISSUE TITLE
Update to publish from release branch

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#2]
It would be good if we create a new branch `release` that we release from. That would make it easy for us to continue dev in `master` and we can push changes to `release` when we are ready to go out in yeoman.

Below are the changes that I'm aware of to make this happen.
- [x] Update [package.json](https://github.com/ligershark/generator-aspnet/blob/master/package.json) with a new version and pointing to the [ligershark repo](https://github.com/ligershark/generator-aspnet).
- [x] Create `release` branch
- [ ] Update [generator-aspnet](https://www.npmjs.org/package/generator-aspnet) to point release branch. Is there any restrictions regarding support for branches? If the publish must be from `master` then we can create a `dev` branch.
- [x] Publish updated changes to [npm generator-aspnet package](https://github.com/ligershark/generator-aspnet).

@shirhatti did I miss anything?

@shirhatti can you add me as an owner on the [generator-aspnet](https://github.com/ligershark/generator-aspnet) package? My npm username is `sayedha`. You should be able to do that with the command `npm owner add sayedha generator-aspnet`.

**Comment by shirhatti** [comment]
@sayedihashimi 

Working on this right now. Just added you as a maintainer on npmjs.
Can you give me admin access to this repo?

**Comment by shirhatti** [comment]
I am trying to set up Travis CI to auto-publish from GitHub to npm for which I need to admin privileges

**Comment by sayedihashimi** [comment]
@shirhatti thanks man! You should already be configured as a contributor.

**Comment by sayedihashimi** [comment]
@shirhatti I added you as admin

**Comment by shirhatti** [comment]
I'm trying to find out whether we can publish to npmjs from a different branch. I'm not able to find any literature on it. Do you have any idea?

UPDATE: Since npm is not linked to git. You can publish at any time by running the `npm publish` command. The third objective you have listed doesn't make much sense at this point.

I have tried to set up Travis such that every time you push to `release` it automatically deploys and I still have some issues. I'm getting this error

```
Skipping deployment with the npm provider because this branch is not permitted to deploy
```

Here is the link to the travis page https://travis-ci.org/ligershark/generator-aspnet

**Comment by sayedihashimi** [comment]
OK thanks for the details. It looks like you got the travis build working. So whenever we merge to the `release` branch it will publish to npm? If so that is great.

Regarding the third objective we would just create a `release` branch in aspnet-vnext-samples and update [index.js](https://github.com/ligershark/generator-aspnet/blob/master/app/index.js) urls to use `release` instead of `master`. Then we can dev in `master` and merge to release when the content should go live.

**Comment by shirhatti** [comment]
Still struggling to get travis to auto-deploy to npm.
Sorry for polluting the commit history, but I need to a few more commits to get i working.

Will work on it later today. 

EDIT: It's working now. Pushing to release will auto-deploy to npmjs now :+1:

**Comment by sayedihashimi** [comment]
@shirhatti cool thanks for all the work. That is great, it will make maintenance easier.

I'll close this item as I think we have addressed all items here.

:shipit:

**Comment by sayedihashimi** [comment]
@shirhatti what's the process to release? I made changes to the vnext samples repo and pushed them to github. After that I updated `package.json` to increase the version number to `0.0.5` and merged the changes to the `release` branch. I verified on [travis build](https://travis-ci.org/ligershark/generator-aspnet/builds) that the build passed and it was updated in [npmjs.org](https://www.npmjs.org/package/generator-aspnet).

When I ran `yo aspnet` and went through the mvc generator I didn't see my changes. I cleared npm cache and re-ran but the result was the same.

**Comment by shirhatti** [comment]
```
npm remove -g generator-aspnet && npm install -g generator-aspnet
```

It worked fine for me. I was able to pull in your changes

**Comment by shirhatti** [comment]
Also, FYI the preferred way to update your version number is use the `npm version` command

https://www.npmjs.org/doc/cli/npm-version.html

**Comment by sayedihashimi** [comment]
@shirhatti thanks I had to execute `npm remove -g generator-aspnet` because I had previously executed `npm link` on a previous dev directory. Everything seems to be working now.

Thanks for letting me know about `npm version` I will use that going forward.

**Comment by sayedihashimi** [comment]
@shirhatti FYI I have created a wiki on how to publish changes https://github.com/ligershark/generator-aspnet/wiki/how-to-publish-changes
