### ISSUE TITLE
Make kpm restore optional during generation ?

### ISSUE THREAD

**Issue by suhasj** [ligershark/generator-aspnet#21]
Creating an application installs it and then runs 'kpm restore' which pulls in packages from the feed defined in the Nuget.config dropped by the template. The feed currently points to vnext and user wouldn't have a chance to change the feed. Can we make it optional so that the user can change the feed and then restore the packages?

**Comment by sayedihashimi** [comment]
Maybe instead of calling `kpm restore` instead after we write the files we should just print a message letting users know how to do the following.
1. Restore packages
2. Build the project
3. Run the project

**Comment by sayedihashimi** [comment]
We should disable automatic package restore and include a message pointing to https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-kpm-to-restore-packages

**Comment by sayedihashimi** [comment]
OK I've made some changes. When you invoke the generators the result is shown in the image below.

![gen-aspnet-01](https://cloud.githubusercontent.com/assets/1283154/4783896/052b71b2-5d3b-11e4-977d-dae0bb6facfc.png)

**Comment by sayedihashimi** [comment]
OK I'm removed the call to `kpm restore` and published to npmjs as version `0.0.11`. Let me know if you have any issues with the updates.a
