### ISSUE TITLE
Making dropping of Nuget.config file optional

### ISSUE THREAD

**Issue by suhasj** [ligershark/generator-aspnet#22]
Currently creating a new application drops Nuget.config and global.json in the root directory. Doing kpm restore, restores the packages from the feed defined in this Nuget.config file and not the Nuget.config defined for the machine. Can we make dropping of this file optional or not drop it at all ?

**Comment by sayedihashimi** [comment]
Sounds good

**Comment by sayedihashimi** [comment]
Do you know of any OSS generators that have similar optional options? I'm looking for an example of how to implement this.

**Comment by sayedihashimi** [comment]
Here is a sample generator with such options https://github.com/yeoman/generator-webapp

**Comment by sayedihashimi** [comment]
When I remove `NuGet.config` from the root and invoke `kpm restore` the result is below for the `MVC` template.

![gen-asp-02](https://cloud.githubusercontent.com/assets/1283154/4784071/2b288d44-5d42-11e4-8c6b-f140202afeed.png)

So it looks like we still need `NuGet.config` or the templates are incorrect.

**Comment by sayedihashimi** [comment]
It's not needed anymore
