### ISSUE TITLE
Update travis build to verify all templates

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#29]
We already have a [travis build in place](https://travis-ci.org/ligershark/generator-aspnet). When there are changes it's cumbersome to verify. It would be good if travis could verify the following continue to work.
- `yo aspnet` creates content for all generators
- `kpm restore` passes for all generators
- `kpm build` passes for all generators
- `k kestrel` successfully starts kestrel on given port for web projects. **_stretch goal**_

I don't know much about travis myself so this is def an area that we can use some help.

**Comment by sayedihashimi** [comment]
@kenwarner I've invited you to generators-contrib group. Can I assign this item to you?

**Comment by kenwarner** [comment]
:accept:

**Comment by sayedihashimi** [comment]
Migrated to https://github.com/OmniSharp/generator-aspnet/issues/25

@kenwarner you never sent over a contribution for this. If you are still interested please send a PR to our new repo https://github.com/OmniSharp/generator-aspnet.
