### ISSUE TITLE
Create empty vNext project (i.e. class library)

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#3]
We should create a template for an empty vNext project. This is basically a class library template.

This template should just create a new folder with the given application name and create a project.json file. I don't think we need to included the `Class1.cs` file in the template. Is there a Sublime snippet to create a C# class? If not we should consider to create one as well. I'll file an issue for us to look into it.
##### project.json

``` json
{
    "dependencies": {
    },

    "frameworks" : {
        "net451" : { 
            "dependencies": {
            }
        },
        "k10" : { 
            "dependencies": {
                "System.Runtime": "4.0.20.0"
            }
        }
    }
}
```

**Comment by spboyer** [comment]
@sayedihashimi submitted PR to generator-aspnet and aspnet_vnext_samples. Did include an empty class file, although (Omnisharp) [https://github.com/OmniSharp/omnisharp-sublime] Sublime addin does have the ability to create new class file based on templates not sure on othere IDEs

**Comment by sayedihashimi** [comment]
@spboyer thanks, I've asked @rustd to review it.

**Comment by sayedihashimi** [comment]
I'm pretty sure this got added already in https://github.com/OmniSharp/generator-aspnet. If not please let me know. Closing now.
