### ISSUE TITLE
There is an error when I generate the project

### ISSUE THREAD

**Issue by winsonet** [ligershark/generator-aspnet#30]
I just install this generator-aspnet, but when I run the below command:

```
yo aspnet
```

and select the project(any projects), there is an error:

```
/usr/local/lib/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/download/index.js:70
            if (opts.extract && (decompress.canExtract(opts.url, mime) || opts
                                            ^
TypeError: Object function Decompress(opts) {
    if (!(this instanceof Decompress)) {
        return new Decompress(opts);
    }

    this.opts = opts || {};
    this.streams = [];
} has no method 'canExtract'
    at Request.<anonymous> (/usr/local/lib/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/download/index.js:70:45)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onResponse (/usr/local/lib/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/request/request.js:832:10)
    at ClientRequest.g (events.js:175:14)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1669:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1564:20)
    at CleartextStream.read [as _read] (tls.js:502:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
```

any ideas?

Thanks!

**Comment by sayedihashimi** [comment]
I cannot reproduce this. What platform are you executing this on?

**Comment by winsonet** [comment]
I am using OS X Yosemite, and the yo and generator-aspnet are latest version

**Comment by sayedihashimi** [comment]
Are you using Sublime Text 3? Do you have mono and python installed?

**Comment by winsonet** [comment]
yes, I have installed everything(include kvm, Kulture...) , but still cannot work, I just doubt that's my environment issue, because I also cannot run the sample project within KVM :(

**Comment by sayedihashimi** [comment]
OK I'm really stumped by this. I cannot repro and I have no idea what could be happening here. I'm running Yosemite as well. I am not well versed in mac development so I'm not sure what the best way for you to debug the issue is. If you could help to figure out the underlying cause that would be awesome. I know that's not what you want to hear, sorry I couldn't be more helpful.

Is there anyone that we can reach out to for help on the issue?

**Comment by sayedihashimi** [comment]
Another question, do you have `git` on the path? After you pick the project it clones a git repo so I wonder if it is tripping up on that part?

**Comment by winsonet** [comment]
Thanks for your help! I will update you if I can solve this.

For your question, you means with the sample project? Yes, I have git these on the path, anyway, I think that's my environment and settings issue, thanks your reply !

**Comment by sayedihashimi** [comment]
I'm not sure if this is still an issue or not, please open an issue in our new repo at https://github.com/OmniSharp/generator-aspnet/issues.
