### ISSUE TITLE
Subgenerators for yo

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/generator-aspnet#33]
We should create some yo subgenerators for asp.net 5. What I would recommend is looking at the templates in the `Add New Item` dialog in VS and create subgenerators for those. That should be our initial release so that we are atleast on par with that.

What I'd love to see after that is to create an additional set of yo subgenerators. Then when a VS release is going to go out we can pickup the files in the subgenerators. 

@kenwarner let me know what you think. I'm excited to try it out and see how the experience feels. I've assigned the item to you.

cc @rustd @johnpapa @shanselman

**Comment by johnpapa** [comment]
I'm creating a HotTowel yo generator. Happy to share it if it helps. It is all client code, other than gulp/karma/node/etc for server processes.

**Comment by spboyer** [comment]
@sayedihashimi @johnpapa created this: https://github.com/spboyer/generator-aspnet-item check it out let me know what you think, uses the vstudio templates from vs15.

**Comment by sayedihashimi** [comment]
They have been added in the new repo https://github.com/OmniSharp/generator-aspnet. Closing.
